name: Nordic
main: me.simplex.nordic.Nordic
version: 0.2.0
website: http://forums.bukkit.org/threads/33060/
author: simplex
load: startup
description: Custom Worldgenerator 
commands:
  nordic:
    aliases: [n,nord, nrd]
    description: Generates a new Nordic-World and ports you into it
    usage: /<command> [worldname] [seed]
permissions:
  nordic.*:
    description: Gives access to the /nordic command
    children:
      nordic.command: true
  nordic.command:
    default: op
    description: gives acced to the /nordic command